### ISSUE TITLE
Lauren Yanko Feedback

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#396]
##### Main Pages (before logging in)
- [x] The main green icons are nice, as I have mentioned before, but I feel that the smaller icons (on buttons as well as at the bottom of the page) are a little too small. 
- [x] The biggest nitpick I have on these main pages is that the buttons are too wide. I get that you are trying to balance out the text above the buttons, but the extra space on the sides of the buttons looks very awkward to me. I would reduce the button width to not much more than the length of the text on the button. 
- [x] Another suggestion is to have the over state be the lighter green and the resting state be the darker green. The buttons don't stand out to me enough with the light green as their resting state color. 

##### TEAM Mentor (after logging in)
- [x] On the Help page, maybe you can create more hierarchy, or at least section off different topics, by adding a colored box in the background for the side bar and a little more color to the main body text being highlighted. 
- [x] Likewise, when I visit the Navigation page, I notice the same thing. I realize that when you mouse over a specific topic, a grey box appears behind it, but the spacing of the three columns (Guidance, Articles, Filters) is very close, so I think you need more of a differentiator. You could also consider condensing the width of each column or making the middle one stand out more with some color. 
- [x] I noticed that the search button does not align with the search bar. 
- [x] I think it could be nice to have the search bar in the Navigation view, or if nothing else a call to action on the search page about the Navigation view. It's not necessarily clear to me that I need to go to the navigate page after I log in, and from QAing courseware, I know our clients don't always get even the simplest concepts without obvious prompting.

**Comment by DinisCruz** [comment]
really cool feedback,

**Comment by luchia** [comment]
These issues have all been addressed.

**Comment by roman87** [comment]
These look good. Marking them to follow up with Lauren when beta Is out. The last one was discussed on the call yesterday. The idea is to actually point the user to search and not to navigate page. Therefore we really want the user to discover it on their own if they want to. We will also explain the Navigate page in the tutorial video.

**Comment by romichg** [comment]
All is fixed.
