### ISSUE TITLE
CR.Beta.4 - Release notes

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#622]
Link from this issue the issues added which represent features worth mentioning (this info will be added to the [release notes](https://github.com/TeamMentor/TM_4_0_Design/releases) and the issue closed when the code has been pushed to beta.teammentor.net)

**Release notes:**
Number of UI fixes, and GraphDB improvements

**Features/Issues:**

* [X] Mouse highlights cross-reference links : #626
* [X] Add metadata Icons to Index, Searches and Article: #577, #574
* [X] Address cases when DB was locking on quick requests:  #504, #515, #604 , #641
* [X] Add metadata information to article (on GraphDB): #631
* [X] Add easy way for user to provide feedback to TM Dev team #624

**Comment by roman87** [comment]
I think its easier to have a label.

**Comment by roman87** [comment]
Also this issue is hard to assign to anyone, and it would kind of pollute the label process we already have.

**Comment by DinisCruz** [comment]
well the idea is that once that issue with a label is closed we add it here, that way you always have the release nodes done

**Comment by roman87** [comment]
Why not just add the issue with the label it to a wiki page :)?

**Comment by DinisCruz** [comment]
I think its working quite nice, look how some topics/items have more than one issue mapped to it.

this way if we keep updating this page as the issues are being ready, it is easy to cut the release (i.e. there is not a lot a work to do at that moment in time)

The other part of the workflow is to move the items around as they go from QA to 'ready for release'

**Comment by roman87** [comment]
If you want to maintain this issue, certainly feel free :). I am using a kabaan board, so I need to use labels to maintain the status. As far as release notes, we don't need to have them for each Beta, we need to have them for a release. Which is something I can do by going through the closed P0 issues.

**Comment by DinisCruz** [comment]
cool, where is the kanban board?

**Comment by roman87** [comment]
You've see it before https://waffle.io/teammentor/master?label=Sprint2&source=TeamMentor%2FTM_4_0_Design

**Comment by DinisCruz** [comment]
code is on master and ready for Beta.4 release

**Comment by DinisCruz** [comment]
and QA tests are passing (which include Design and GraphDB tests):

![image](https://cloud.githubusercontent.com/assets/656739/6909307/92ef0ad8-d73c-11e4-91be-91b23ca59791.png)

**Comment by DinisCruz** [comment]
Marked master as CR.Beta.4

![image](https://cloud.githubusercontent.com/assets/656739/6924397/2da3a1fe-d7d0-11e4-9be3-087ce945fee3.png)
