### ISSUE TITLE
Lauren Yanko Feedback

### ISSUE THREAD

**Issue by luchia** [TeamMentor/TM_4_0_Design#658]
- [x] The very first photograph (with text "Instant resources that bridge the gap between developer questions and technical solutions") seems much darker than the others. That said, I actually think this darker photo allows for a better contrast with the button and white text that overlay it. Would you consider making all photos this darker grayscale?

- [x] I noticed that the columns/content on pages Docs, Sign Up and Login do not line up with the top nav bar as they do on the About and Features pages. Widening the left column on the Docs page, for example, will both align that column with the top nav bar and also likely make enough room on the buttons for some text to run one line (as opposed to having one word fall to its own line). What do you think? Let me know if this is confusing.

- [x] For the footer I would left-align each column instead of center-aligning so that the icons and text line up.

**Comment by luchia** [comment]
I thought all these comments were valid @roman87, so I made the additions on the branch and have created a PR for @DinisCruz to merge. Assigning to @roman87 for QA.

**Comment by DinisCruz** [comment]
ok, I just fixed a couple tests and merged that code into dev

**Comment by roman87** [comment]
I like the darker color photos. 

Now for items 2 and 3, I am not sure what was done. I don't see any difference. @luchia can you point them out? Maybe my non designer eye does not pick them up :)
![selection_175](https://cloud.githubusercontent.com/assets/1326120/6995094/e80bb6da-daff-11e4-8b73-1123f7db3924.png)

**Comment by luchia** [comment]
Did you pull from Dev? It's on there -

![screen shot 2015-04-07 at 5 40 36 am](https://cloud.githubusercontent.com/assets/4547737/7011004/e44e8136-dce8-11e4-92dd-fa9007c19ee9.png)
![screen shot 2015-04-07 at 5 40 42 am](https://cloud.githubusercontent.com/assets/4547737/7011005/e4cfe08c-dce8-11e4-9c44-4b1c0627a87e.png)

**Comment by DinisCruz** [comment]
Latest changes pushed by @luchia are now on master and dev

**Comment by roman87** [comment]
Ok so the alignment seems good. I still don't see any difference for the footer left-alignment. The version number is of however:
![selection_176](https://cloud.githubusercontent.com/assets/1326120/7014278/c68d89a6-dc90-11e4-89cb-940b85b54446.png)

**Comment by luchia** [comment]
I changed the margin in the browser, do you think this looks better?

![screen shot 2015-04-07 at 9 17 22 am](https://cloud.githubusercontent.com/assets/4547737/7014336/094dd34c-dd07-11e4-9fb4-072708831256.png)

Or we could center it to the logo but I think left aligned like the rest of the text is better -

![screen shot 2015-04-07 at 9 19 04 am](https://cloud.githubusercontent.com/assets/4547737/7014344/2a3f7fe2-dd07-11e4-95d9-acf756610d47.png)

**Comment by roman87** [comment]
I don't think it looks nice with bigger margins. I think if we need to have a different solution. Anyways I am going to mark this for follow up with Lauren as all the points in the issue had been addressed. 
Lets open another issue for the TM Version so we can track it better.

**Comment by luchia** [comment]
I opened an issue and have assigned to you to follow up with Lauren.

**Comment by yankola** [comment]
An additional comment on the footer: 
Footer should appear on all pages except for the search and index page.

**Comment by roman87** [comment]
Assigning back to @luchia

**Comment by luchia** [comment]
Okay, I think I got all of the pages that I needed to -

![screen shot 2015-05-08 at 11 22 39 am](https://cloud.githubusercontent.com/assets/4547737/7529095/9b2608ac-f576-11e4-8d95-b2e35baaccd9.png)
![screen shot 2015-05-08 at 11 35 25 am](https://cloud.githubusercontent.com/assets/4547737/7529096/9b524a70-f576-11e4-903d-dc5222d9a757.png)

![screen shot 2015-05-08 at 11 38 40 am](https://cloud.githubusercontent.com/assets/4547737/7529118/dbd56334-f576-11e4-8f34-e9e79ec16ab0.png)
![screen shot 2015-05-08 at 11 39 03 am](https://cloud.githubusercontent.com/assets/4547737/7529119/dbd651d6-f576-11e4-8d74-03ac34ee4895.png)
![screen shot 2015-05-08 at 11 39 08 am](https://cloud.githubusercontent.com/assets/4547737/7529120/dbd69ec0-f576-11e4-9914-6b8f18610441.png)

**Comment by luchia** [comment]
PR to come at the end of my day.

**Comment by roman87** [comment]
So on DOCS pages, if the user is logged in, the     Security Innovation 2015. All rights reserved. is not underlined.
![selection_219](https://cloud.githubusercontent.com/assets/1326120/7547603/b9c11052-f5be-11e4-976a-6927154c9e60.png)

But when the user is not logged in, It is:

![selection_220](https://cloud.githubusercontent.com/assets/1326120/7547605/c15cbaaa-f5be-11e4-9697-89ba52052dc8.png)

**Comment by luchia** [comment]
Fixed -

![screen shot 2015-05-12 at 9 57 23 am](https://cloud.githubusercontent.com/assets/4547737/7577588/4f8f7350-f88d-11e4-8895-9668b378498d.png)

**Comment by roman87** [comment]
Looks good, will follow up with @yankola  once in beta.

**Comment by roman87** [comment]
Hey @yankola could you take a look at the latest beta and let us know if this has all been resolved to your satisfaction?

**Comment by romichg** [comment]
Closing due to TTL
