### ISSUE TITLE
CR.Beta.6 - Release notes

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#675]
Link from this issue the issues added which represent features worth mentioning (this info will be added to the [release notes](https://github.com/TeamMentor/TM_4_0_Design/releases) and the issue closed when the code has been pushed to beta.teammentor.net)

**Release notes:**
Multiple UI changes and bug fixes

**Features/Issues:**

* [X] Changing query number in URL clears UI #627
* [X] Consolidate icons into TM typeface #634
* [X] Update the Jade footer to appear more polished #668
* [X] Fix to update the width of the input field #687 and #699
* [X] Password reset confirmation page is broken #665
* [X] Sort queries and filters #557

**Comment by DinisCruz** [comment]
QA is passing

![image](https://cloud.githubusercontent.com/assets/656739/7148755/fa826d30-e2fd-11e4-9480-ff9ecbda1c5b.png)
