### ISSUE TITLE
CR.Beta.7 - Release notes

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#703]
Link from this issue the issues added which represent features worth mentioning (this info will be added to the [release notes](https://github.com/TeamMentor/TM_4_0_Design/releases) and the issue closed when the code has been pushed to beta.teammentor.net)

**Features/Issues:**
* [X] Add support for using 3.5 Article Tags in search results weights #704
* [X] Need to have an Icon for "Vulnerability" Type articles #710
* [X] Clicking next to the magnifying glass icon does not put cursor in the text box #687
* [X] It is possible to create hundreds of temporary articles in the server using TM. #697
