### ISSUE TITLE
CR.Beta.8 - Release notes

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#719]
Link from this issue the issues added which represent features worth mentioning (this info will be added to the [release notes](https://github.com/TeamMentor/TM_4_0_Design/releases) and the issue closed when the code has been pushed to beta.teammentor.net)

**Features/Issues:**
* [X] Add syntax colouring to Jade Article's rendering #413
* [X] Refactor ArticleHTML and Search Artifacts creation out of the GraphDB #727
* [X] Add new icons to Getting Started summary element #722
* [X] Formatting issue on the search bar #732

**Comment by DinisCruz** [comment]
@roman87 I think we are ready for this one

I merged all @luchia changes and the tests are all passing locally. Travis is a bit slow at the moment, but I should be able to confirm that all is ok in a bit

And once it all passes in travis I will move the code to master

**Comment by DinisCruz** [comment]
all tests passed 
![image](https://cloud.githubusercontent.com/assets/656739/7382763/ce8f3bc2-ee0b-11e4-8985-4a58c7d6c7d6.png)

all master branches are now on CR.Beta.8
