### ISSUE TITLE
CR.Beta.9 - Release notes

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#739]
Link from this issue the issues added which represent features worth mentioning (this info will be added to the [release notes](https://github.com/TeamMentor/TM_4_0_Design/releases) and the issue closed when the code has been pushed to beta.teammentor.net)

**Release notes:**
....

**Features/Issues:**

**In QA** (this is the first place to add the issue link)
* [ ] TM article redirection is not happening upon login #615
* [ ] Create custom set of icons #634
* [ ] Docs pages need to be installed on and served from the local cache, including images #664 
* [ ] Add link to allow users to add comments re articles #713 
* [ ] Make Customer View easily customisable #721
* [ ] Add SSO capability to Jade and Flare #726 
* [ ] Make alerts have clearer distinction from the application #733
* [ ] Fix Flare docs navigation #737 
* [ ] Add support for simple /a/{ref} article navigation #738 
* [ ] GraphDB Crashes on Windows when going through the UI #740
* [ ] Create Icons for "Phase" as well #750
* [ ] Searching for HTML tags causes large number of results, it's slow and causes DoS #753 
* [ ] Font issue on the menu after logging in #758 
* [ ] Technology Independent and WCF icons are the same. #780

**Comment by DinisCruz** [comment]
We're green, cutting the release

![image](https://cloud.githubusercontent.com/assets/656739/7623248/195507d4-f9d0-11e4-9636-be400098cbfd.png)
