### ISSUE TITLE
Populate the referrer HTTP header when tracking activities.

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#864]
One of the reasons why we are not seeing the traffic from TEAM Professor (i.e users that hit TP and then went to TEAM  Mentor) is because our tracking method is not setting up the referrer HTTP header, according to the documentation : 

urlref — The full HTTP Referrer URL. This value is used to determine how someone got to your website (ie, through a website, search engine or campaign). (Taken from http://developer.piwik.org/api-reference/tracking-api).

**Comment by michaelhidalgo** [comment]
With Pull request https://github.com/TeamMentor/TM_Website/pull/2

**Comment by michaelhidalgo** [comment]
@DinisCruz  can you please review this small fix?

**Comment by DinisCruz** [comment]
this has been merged 

@michaelhidalgo small thing, remember to cross-link the issue from the PR, so that we get a quick view of it from here:

![image](https://cloud.githubusercontent.com/assets/656739/8278586/aa32a00a-18c4-11e5-905e-98151b379dbe.png)

**Comment by romichg** [comment]
Once piwik box is up, lets test this and make sure all is working.

**Comment by roman87** [comment]
we actually need to make sure that we are tracking everything we need in flare. 
-[ ] searches and search queries
- [ ] navigation queries and filters
- [ ] article views
- [ ] we track the username in piwik (when we have a username)
- [ ] we track the browser fingerpring/cookie we gather for the 5 free articles. 
- [ ] we tie the fignerpring to the username when available

**Comment by romichg** [comment]
This is done.
