### ISSUE TITLE
Add piwik tracking to Flare/update Jade analytics

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#934]
we actually need to make sure that we are tracking everything we need in flare. 
- [x] searches and search queries  - What are visitors searching for, searches per visitor
  - [ ] navigation queries and filters - trending navigation links, trending filters.
- [x] article views - article views per user, total article views, trending articles
- [ ] abandoned searches and navigation - searches and navigation that did not lead to an article view. For example, a search and filtering operation that resulted in no article views and an eventual successful one after words. (we may need graph DB social features for this) 
- [ ] time spent on each article
- [x] be able to recognize a returning visitor

For both Flare and Jade
- [x] we track the username in piwik (when we have a username), such that we tie the username to the visitor ID.
- [ ] we track the browser fingerpring/cookie we gather for the 5 free articles. 
- [ ] we tie the fignerpring to the username when available

**Comment by michaelhidalgo** [comment]
Hi @roman87 , are we going to use the cloud-based version of Piwik or a custom server?

It seems like our trial at piwik ended.

**Comment by romichg** [comment]
We will use our own server, I just need to get one first. Hopefully in couple of days I will have that ready.

**Comment by romichg** [comment]
The current solution will work for now. I am moving this to sprint 3 and updating the issue with more requirements.

**Comment by romichg** [comment]
some of the important ones are being tracked, the rest can be done later.
