### ISSUE TITLE
barco de carga (cargueiro) of Flare issues (Dinis/Michael)

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#943]
- [x] back button does not work (dinis/michael)
- [x] Selecting a filter first, is a bit slow and no intuative way of showing that it is working (dinis)
- [x] showing the bottom footer with results per page and page numbers is useless on a page with 2-3 items (dinis/michael)
- [x] At what point should we clear the search box (homepage, index page) (dinis/michael)
- [x] flicker when loading index. maybe not show any articles untill they finish loading? (dinis/michael)
- [x] remove "QUERY HAS" and display "SHOWING N OUT OF X ARTICLES" REMOVE THE # OF articles per page (dinis/michael)
- [x] change "All" to "All Technologies". Change the search box to "Search All of TEAM Mentor" and change to indicate technology when selected ex "Search HTML 5" (michael)
- [ ] add index to root breadcrubm and change title to "DIRECTORY" on the left-hand side (How to get back to the index after search) (Dinis) - _this is not going to be done as it is not necessary with current breadcrumb solution_
- [x] technology dropdown needs to be independent of the filters, such that  only when user hits enter (or search button) on the search bar the technology filter is applied
- [x] Selecting filter set and then doing a search doesn't work and vice verse. At that point Index button stops working (Dinis)
- [x] Searching within an article does not make use of technology selector [should be solved with URLs](Dinis)
- [x] https://tmdev01-beta.teammentor.net/angular/user/main shows nothing (waiting for merge Dinis)
- [x] icons on badges are wrong (Dinis/Michael)
- [x] Number of articles per page doesn't work/should be global (Michael/Dinis)
- [x] back to the top doesn't work (Dinis/Michael) 
- [ ] Selecting multiple filters should scroll the list to the top (also on https://github.com/TeamMentor/TM_4_0_Design/issues/946)
- [x] HItting "See For Yourself" on the landing pages brings up slightly scrolled down signup page. Signup page should always be scrolled up.
  ![selection_009](https://cloud.githubusercontent.com/assets/1326120/9611554/5048ff7c-50ae-11e5-8f5e-7cbf98a82b27.png)
- [x] successful sign up should put the user to the index page, not the user page

Requests from @luchia in Slack
- [x]  Can we make JS change the height of .scrolling-results from the defined height to 75% when active-filters are present on the page? And change it back to the original height (in the css) when active-filters are not present?
- [ ]  The scrollbars are now always visible. The class you will need to hide them on is .application-scroll. This will solve the 'text jumping' bug. (#1048)
- [ ]  The breadcrumbs need .active assigned to the most recent breadcrumb item. This will need to be removed when subsequent items are added (and applied to the newest). (#1049)
- [ ]  We need to add 'Page ' to the page number dropdown (pagination)  _not sure what this is, but I think this was done_ @luchia can you clarify? (#1050)
- [x]  I noticed that our alert messages on login and sign up use filler text. We'll need to fix this for release
- [x]  We need to add the icons names to the article-metadata on the article view. I have added filler text ('Hi') for the time being.
- [x]  Results per page should be 10 by default. I have done the HTML for this, you guys will just need to wire it up now.
- [x] Need to work out a way to get JS to handle the height of the .article-boxes. When they are in a single line, there should be no height assigned. But when they are in a grid, they should have a min-height: 255px or something similar. Any ideas? I'm tearing my hair out trying to get it to work with CSS alone.

**Comment by romichg** [comment]
Closing. This was ether done, tracked elsewhere or decided not to be done.
