### ISSUE TITLE
Known 4.0 Flare  issues

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#984]
- [x] 1.  fix breadcrumbs on back and direct link (no breadcrumb history is currently maintained) _(mostly  done #1004 )_
- [x] 2. fix left-hand side back button (to mirror going up a breadcrumb)  (#955)
- [x] 3. add words to text prediction (currently prediction only works for keywords)
- [x] 4. fix technology dropdown (currently the size is fixed, should be dynamic like amazon) (https://github.com/TeamMentor/TM_4_0_Design/issues/969)
- [x] 5. don’t lose Phase and Type when technology changes on drop down
- [x] 6. update searchbar with breadcrumb selection
- [x] 7. User UI update to include a TOC
- [x] 8.  ordering of articles does not work in Guides (#1009)
- [x] 9. Back  button does not work on Guides. (#1030)
- [x] 10. Number of articles displayed is always = to total (_almost done, some issues in_ #922)
- [x] 11. Words break in the middle in the article snippet (#903)
- [x] 14. Guides flicker on link _(this is a lot less importaint, now that we stay in guides)_
- [x] 15.  find root cause of article not showing bug
## Will not be fixed this release: 

Search is always on the index (#948)
Search shows only the top queries on the left hand side, no 2nd or 3d level (#951)
Prediction doesn't work with technology selected
Recent search terms don't update (#1031)
Fix ability to colapse filters (#971)
