### ISSUE TITLE
Jason's comments

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#994]
- [x] 1.  Share button doesn’t do anything on click (#985)
- [x] 2.  The heart icon isn’t intuitive for the guide. Maybe an open book? (#986)
- [x] 3.  When clicking through guide articles, is it possible to keep the ToC shown? Maybe that’s what you mean by one of your bullets below? Actually it does seem to stay up sometimes but it is clunky in that it disappears and re-appears with full layout refresh. Then on some articles it doesn’t come up at all. (https://github.com/TeamMentor/TM_4_0_Design/issues/863#issuecomment-140446743)
- [x] 4.  Welcome to TEAM Academy seems strange since its just TM that’s being used. Unless you are planning on adding links/information from TP?  (#987)
- [x] 5. TM icon on the top left is not clickable. (#988)
- [x] 6. The profile icons isn’t intuitive, since you don’t have any profile features in place yet. Probably a search icon (e.g. magnifying glass) would make more sense at the moment.(#989)
- [x] 7. The i icon doesn’t scream help to me and since the UI is so much like the guide I had to click both a few times to tell the difference - oh yeah that’s the docs! I think the this could be made more intuitive. Maybe a question mark? (#990)
- [x] 8. Also first heading/Title should be clear that its documentation you are looking at. (#991)
- [ ] 9.  Can you add popups for the icons? For instance I clicked the ‘power’ icon on far right and was surprised to be logged out. (#1001)
- [ ] 10. Maybe a confirmation on this one as well? (#993)
- [x] 11.  The arrow on the index doesn’t do what I would expect. I do expect it to go up a level (maybe change this to an arrow that points left then up?) but didn’t expect it to do the same as back button. I kept clicking and it eventually brought me to the login screen which was really wierd. (#995)
